# Generated by Django 2.0.4 on 2019-04-01 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('AssetManage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='名称')),
                ('file_type', models.CharField(choices=[('网络设备', '网络设备'), ('业务系统', '业务系统'), ('漏洞列表', '漏洞列表')], max_length=50, verbose_name='类型')),
                ('file', models.FileField(upload_to='files/', verbose_name='批量文件')),
                ('update_data', models.DateField(auto_now=True, verbose_name='更新日期')),
                ('action_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='asset_files_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanner_name', models.CharField(max_length=50, verbose_name='节点名称')),
                ('scanner_type', models.CharField(choices=[('WEB', (('AWVS', 'AWVS'),)), ('System', (('Nessus', 'Nessus'),))], max_length=50, verbose_name='节点类型')),
                ('scanner_url', models.URLField(max_length=50, verbose_name='节点地址')),
                ('scanner_status', models.CharField(choices=[('启用', '启用'), ('禁用', '禁用')], default='禁用', max_length=50, verbose_name='节点状态')),
                ('scanner_apikey', models.CharField(max_length=100, verbose_name='API_KEY')),
                ('scanner_apisec', models.CharField(blank=True, max_length=100, verbose_name='API_SEC')),
                ('scanner_des', models.TextField(verbose_name='节点描述')),
                ('scanner_addtime', models.DateField(auto_now_add=True, verbose_name='开始时间')),
                ('scanner_updatetime', models.DateField(auto_now=True, verbose_name='结束时间')),
                ('assetType', models.ManyToManyField(limit_choices_to={'parent__isnull': False}, related_name='scanner_assettype', to='AssetManage.AssetType', verbose_name='扫描范围')),
            ],
        ),
        migrations.CreateModel(
            name='ScannerPolicies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies_name', models.CharField(help_text='扫描策略为扫描器策略名称', max_length=50, verbose_name='策略名称')),
                ('policies_key', models.CharField(blank=True, help_text='AWVS扫描器需填写，全扫描编号为11111111-1111-1111-1111-111111111111', max_length=50, null=True, verbose_name='策略编号')),
                ('scanner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_for_scanner', to='SeMFSetting.Scanner', verbose_name='节点关联')),
            ],
        ),
    ]
